### ISSUE TITLE
Plugin does not work with NativeScript 3.0

### ISSUE THREAD

**Issue by keepCreate** [manijak/nativescript-carousel#22] opened 2017-05-03 07:59 UTC
how can i deal it , Thank you!

**Comment by manijak** [comment] 2017-05-03 12:57
The plugin, for now, does not work on 3.0. Update will come after 3.0 becomes more stable.

**Comment by danielgek** [comment] 2017-05-03 16:16
@manijak are you working on this ?

**Comment by danielgek** [comment] 2017-05-03 16:20
sorry just saw that you updated 3 hours ago xD but nativescript 3 is out :P

**Comment by manijak** [comment] 2017-05-03 19:01
@danielgek no problem. As soon as I get some time I will try to get it fixed. I don't usually jump to new versions straight away... especially when they are very buggy 😄

**Comment by MattNer0** [comment] 2017-05-05 12:34
I'm trying to fix this plugin and make it work with nativescript 3.0
Android side is pretty much done

**Comment by manijak** [comment] 2017-05-05 13:14
Awesome @MattNer0 thanks a bunch :)

**Comment by sitefinitysteve** [comment] 2017-05-08 04:27
@MattNer0 Any chance of checking in anything you have on Android so I can look at iOS?

**Comment by MattNer0** [comment] 2017-05-08 10:06
@sitefinitysteve I forket it here https://github.com/MattNer0/nativescript-carousel

**Comment by sitefinitysteve** [comment] 2017-05-08 14:27
@MattNer0 Yeah I saw the fork when I posted it, but just didn't seem to have the updated property syntax.  @manijak Are you opposed to moving to Typescript at all?

**Comment by MattNer0** [comment] 2017-05-08 15:37
@sitefinitysteve iOS works better than Android right now :smile: 

With Android I'm getting a `"Cannot read property 'nativeSize' of undefined"` exception after I call the `removeChildren()` method. I'm trying to understand what's wrong with that.

**Comment by sitefinitysteve** [comment] 2017-05-08 15:41
We can apparently get help direct from the team in the NS slack channel, are you a member?

**Comment by MattNer0** [comment] 2017-05-08 17:16
@sitefinitysteve Nope and I actually think the problem is not related to this plugin. Did you try it by any chance?

**Comment by sitefinitysteve** [comment] 2017-05-08 17:17
I didn't try your mods, I actually had to revert back to 2.5 due to needing this plugin on a deadline :/

**Comment by manijak** [comment] 2017-05-08 19:07
@sitefinitysteve If it makes things easier with TypeScript, go ahead. I would not mind.
I'm just swamped with work for the time being. Sorry about that.

**Comment by sitefinitysteve** [comment] 2017-05-08 19:21
@MattNer0 How are you with Typescript...?  Do you want to get this plugin working on v3 in pure JS then I'll convert to TS?

**Comment by EddyVerbruggen** [comment] 2017-05-12 05:44
Hey guys, if you need help let me know.

**Comment by manijak** [comment] 2017-05-12 07:40
@MattNer0 mate are you close to a PR any time soon? So that we can take a look as to where the issue is with the `removeChildren()` function?

**Comment by MattNer0** [comment] 2017-05-12 12:18
@manijak Ok I could do a PR but there are still some issues I think.

I was trying to add PageTransformer animations through this plugin: [ViewPagerTransforms](https://github.com/ToxicBakery/ViewPagerTransforms) and there's a strange glitch happening when new items are pushed to the Carousel.

**Comment by manijak** [comment] 2017-05-12 13:51
Great. Just please don't and any additional plugins until we get 3.0 working.

**Comment by EddyVerbruggen** [comment] 2017-05-14 13:34
@MattNer0 For my purposes your fork works perfectly, thank you!

**Comment by developper89** [comment] 2017-05-25 10:51
still not working on android for Nativescript 3.0 ...

**Comment by manijak** [comment] 2017-05-25 12:15
If you download the master from this repo, it will work. but we have not published yet to npm. There are still some minor issues with initial values from xml on some properties.

**Comment by manijak** [comment] 2017-05-26 21:33
Just released v3 🎉

**Closed by manijak** 2017-05-26 21:33 UTC
Labels: bug
