### ISSUE TITLE
Error: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!

### ISSUE THREAD

**Issue by marast78** [manijak/nativescript-carousel#113] opened 2019-06-12 14:59 UTC
I'm using Android, {N} 5.3.4. My issue occurs only if I fetch data from remote API. I know why it happens but I have no knowledge, how I can fix it.

Below you can find exception thrown by the application :arrow_down: 

`System.err: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 5 Pager id: 7 Pager class: class android.support.v4.view.ViewPager Problematic adapter: class com.tns.gen.android.support.v4.view.PagerAdapter_index_240_28_CarouselPagerAdapterClassInner
System.err: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1143)
System.err: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
System.err: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:87)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.VerticalScrollView.onMeasure(VerticalScrollView.java:147)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err: 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err: 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err: 	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
System.err: 	at android.view.View.measure(View.java:23169)
System.err: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2718)
System.err: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

**Comment by manijak** [comment] 2019-06-17 06:53
Think you need to provide some code, how do you bind data to the Carousel?

**Comment by marast78** [comment] 2019-06-17 07:07
Hi, 

below some parts of my code which should help you. The issue occurs not permanently so I think that there can be something wrong between rendering UI and binding logic data. My data is got via HTTP from outside API but when I use local array everything works fine.

    protected pets: Array<any> = [];

    ngOnInit(): void {
        this.getPets();
    }

    public getPets()
    {
        this.isLoadingPets = true;
        this.httpService.get('pet', { limit: 5 })
            .subscribe((result) => {
                this.isLoadingPets = false;
                const response: any = result;
                const pets: any = response.data.data;
                this.setPets(pets);
            }, (error) => {
                this.isLoadingPets = false;
                this.dialog.showError(
                    this.httpService.getError(error)
                );
         });
    }

    private setPets(pets: Array<any>) {
        for(let i=0; i<pets.length; i++) {
            this.pets.push(pets[i]);
        }
    }

**Comment by manijak** [comment] 2019-06-17 07:35
Can you try instead of `this.setPets(pets);` do `this.pets = pets;`

**Comment by marast78** [comment] 2019-06-17 09:48
Done but it didn't help.

**Comment by HaikelPixpay** [comment] 2019-06-26 16:10
have you find a solution, I have the problem too.

**Comment by marast78** [comment] 2019-06-26 19:46
@HaikelPixpay nope

**Comment by HaikelPixpay** [comment] 2019-06-27 10:41
I tried with the latest version, I have the same problem. The plugin works perfectly when the carousel is in the default page, but when I use navigation, an error occurs on Android and in IOS the elements stack up.

**Comment by bufke** [comment] 2019-06-29 15:05
Is this the same bug? #101

Maybe not framework specific. If the items are static it's fine, as soon as they change it breaks. I haven't been able to work around this.

**Comment by HaikelPixpay** [comment] 2019-07-03 07:35
I removed [ngSwitch] from the parent and switched to the nested router and now it works.

**Comment by manijak** [comment] 2019-07-03 08:07
@HaikelPixpay Could you please elaborate? If this is a valid workaround I could post it in the readme. 

I'm having a hard time in reproducing this issue, so if anyone could provide a demo app it would help.

**Comment by manijak** [comment] 2019-07-18 07:50
Duplicate of https://github.com/manijak/nativescript-carousel/issues/101

Closing

**Closed by manijak** 2019-07-18 07:50 UTC
Labels: android, angular, question
