### ISSUE TITLE
iosOverflowSafeArea works incorrectly

### ISSUE THREAD

**Issue by 3DtuningProduction** [manijak/nativescript-carousel#102] opened 2019-03-11 17:38 UTC
Hi 
Trying to make a full-screen carousel
Very strange error is obtained
1 screen
http://prntscr.com/mwfq5z
2 screen
http://prntscr.com/mwfqze
How do you think this problem can be solved?
Thank you in advance

**Comment by manijak** [comment] 2019-03-11 18:45
Hmmm. I've recently had some issues similar to this. Have no idea what is causing it. Could be the iphone x safe-area calculation.

**Comment by manijak** [comment] 2019-07-18 08:03
Duplicate of https://github.com/manijak/nativescript-carousel/issues/114
Closing

**Closed by manijak** 2019-07-18 08:03 UTC
Labels: duplicate
